export const GET_USER_DEPARTMENT_REQUEST = 'GET_USER_DEPARTMENT_REQUEST';
export const GET_USER_DEPARTMENT_SUCCESS = 'GET_USER_DEPARTMENT_SUCCESS';
export const GET_USER_DEPARTMENT_FAILURE = 'GET_USER_DEPARTMENT_FAILURE';

export const GET_PRODUCT_SQI_REQUEST = 'GET_PRODUCT_SQI_REQUEST';
export const GET_PRODUCT_SQI_SUCCESS = 'GET_PRODUCT_SQI_SUCCESS';
export const GET_PRODUCT_SQI_FAILURE = 'GET_PRODUCT_SQI_FAILURE';
