export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const SET_PRODUCTS_FILTER_DEFAULT = 'SET_PRODUCTS_FILTER_DEFAULT';
export const SET_PRODUCTS_FILTER = 'SET_PRODUCTS_FILTER';
export const ADD_PRODUCTS_AGGREGATES = 'ADD_PRODUCTS_AGGREGATES';
