export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';

export const GET_PLATFORM_TYPES_REQUEST = 'GET_PLATFORM_TYPES_REQUEST';
export const GET_PLATFORM_TYPES_SUCCESS = 'GET_PLATFORM_TYPES_SUCCESS';
export const GET_PLATFORM_TYPES_FAILURE = 'GET_PLATFORM_TYPES_FAILURE';
